[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "v1nizin", email = "viniwick@outlook.com"},
]
dependencies = [
    "django>=4.2",
]
requires-python = ">=3.10"
license = {text = "MIT"}
